### PR TITLE
Getting Started with a different layout

### PR DESCRIPTION
**Pull request by jsanz**

### CODE REVIEW

**Comment by jsanz** [comment]
@rochoa can I have write permissions on this repo so I can work with @ztephm directly on a branch here instead of working on a fork on my account?

**Comment by rochoa** [comment]
😢 I can't. It looks like even I created the repo, I'm no longer able to change its settings.

I guess you have yo go the @alberhander route.

**Comment by alberhander** [comment]
@rochoa @jsanz I gave the `CARTO-team` Write access to this repo. Let me know if you need anything else.

**Comment by jsanz** [comment]
Great, thanks @alberhander, I'll close this PR then and create a new one from the branch in the repo, nice!!

**Pull request closed without merging**
