### PR TITLE
Training v2

### PR DESCRIPTION
**Pull request by ztephm**
Look ok @rochoa @jsanz ?

### CODE REVIEW

**Comment by jsanz** [comment]
@ztephm the content is perfect, but I have a few comments:

* We need to update the `README.md` in the frontpage to point to these new material
* I've created a new PR against your branch just updating the first file. The changes I made are tailored to make it more readable, but also fixing some small markdown issues like heading numbers, code formatting and so on. Check [the result](https://github.com/CartoDB/carto-vl-training/blob/e53ee15e0b769de5f7e5b0eebc04004c5e2725cc/training-v2/01-getting-started.md) and let me know if you agree with the approach. Adapting the rest of the code to these layout shouldn't take much, Visual Studo Code helps to lint the markdown code.

**Comment by rochoa** [comment]
Sorry, it took me a bit longer check this one.

This is a huge improvement over my initial work. Much more detailed. Kudos, @ztephm!

As @jsanz is saying, I would make this the default and won't call it `v2`.

❤️

**Comment by ztephm** [comment]
Great, thanks @rochoa ! We are making some style updates in another branch and will make this the default instead of v2.

**Comment by jsanz** [comment]
@rochoa can you take a look to the final write up that @ztephm did on this branch. The idea is to switch from the `commit` approach to a more traditional `prose` one :smile: 

For the records, @ernesmb already delivered this material to a partner last week and the feedback from him and the attendees was really good, so major kudos to you and @ztephm for putting this all together, this is going to be used extensively!

**Comment by jsanz** [comment]
@rochoa any feedback about this? If you are OK I'd like to set up this branch as the default training shape, as @ernesmb already validated with a partner that the write up is :ok_hand:

**Comment by rochoa** [comment]
The material is now much better organized.

My concern right now is about what was the original target audience and why I created the training. My thinking back then:

> The existing CARTO VL documentation is a useful resource, however, **this training is derived from the future version of the CARTO VL documentation and guides**.

 I don't know if that has changed or what's the intention from now on. Don't take me wrong, I find the work here amazing and you know much more than I do about doing training and the audience. However, as the documentation and guides in CARTO VL improved a lot for the public release, this training material, sometimes, duplicates, some of the content. And that's totally OK, but we just need to be aware.

**Comment by jsanz** [comment]
Totally understandable @rochoa and actually we were already discussing that at some point this material should move to our Developer Center so at that moment we'll have to ensure that it does not overlap with existing guides there.

At the end, I guess, we need to coordinate the DC content in a way that we can decide depending on how much time do we have, which is our audience, logistics of the training session and so, which set of guides make sense to deliver.

**Comment by ztephm** [comment]
OK thank you for the feedback @rochoa - for now do you think it's OK to merge this? Or alternatively just leave it as a branch and mention the branch in main README?

**Comment by rochoa** [comment]
This seems to be a great resource for you, it's well organized and will serve its purpose. I would merge it.

**Pull request merged**
