### PR TITLE
v2 training on a different layout 

### PR DESCRIPTION
**Pull request by jsanz**
@ztephm I've uploaded the branch with a better new name so we can work here this week.

### CODE REVIEW

**Comment by ztephm** [comment]
thanks @jsanz - I agree w/removing the numbers as long as people have links & enough step titles to easily find their place again if they fall behind during a training. I updated the README also. 

I will add section links to the README and step links in the sections, but we have to merge this first so I can get the correct urls, right?

**Comment by jsanz** [comment]
It should't be needed, you can make relative path links to your articles on the readme that work on your branch and in the master one after merging. You just need to remove the `training-v2` folder as everything is at the root and then add links as `[Getting Started](01-getting-started.md)` on your `README.md` file.

**Comment by ztephm** [comment]
Look ok to merge now @jsanz ?

**Comment by jsanz** [comment]
let me check-out the branch tomorrow and see it on my own environment, there's plenty of changes here :smile:

**Comment by jsanz** [comment]
ey @ztephm I understand the content inside the `training-v2` folder can be safely removed as your sections are all in the root of the repo right? then go ahead, remove that folder, and merge this branch with the `training-v2` branch and we can finish the discussion about the final shape of the training there, the purpose of this PR is fulfilled after I run a linter on the markdown files to remove trailing spaces and other small cosmetic improvements.

**Pull request merged**
